config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'como_funciona/index'
  get 'meu_perfil/index'
  get 'eu_quero/index'
  get 'meus_itens/index'

  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meus_iten.rb
class MeusIten < ApplicationRecord
end

app/models/meus_produto.rb
class MeusProduto < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

has_attached_file :avatar, styles: { medium: "400x400>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
       		validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
#protect_from_forgery with: :exception

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :endereco, :telefone])
  end
end

app/controllers/como_funciona_controller.rb
class ComoFuncionaController < ApplicationController
  def index
  end
end

app/controllers/eu_quero_controller.rb
class EuQueroController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meu_perfil_controller.rb
class MeuPerfilController < ApplicationController
end

app/controllers/meus_itens_controller.rb
class MeusItensController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nome, :tipo, :estado, :descricao, :doador, :avatar)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nome, :tipo, :estado, :descricao, :doador, :avatar)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/como_funciona_helper.rb
module ComoFuncionaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meu_perfil_helper.rb
module MeuPerfilHelper
end

app/helpers/meus_itens_helper.rb
module MeusItensHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/meus_itens/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<h1>Produtos</h1>

<table>
  <thead>
    <tr>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Nome</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Tipo</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Estado</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Descrição</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Doador</th>
      <thcolspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% if user_signed_in? && product.doador == current_user.nome %>
      <tr>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.nome %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.tipo %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.estado %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.descricao %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.doador %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= link_to 'Mostrar', product %></td>
	<td>&emsp;</td>

          <td><%= link_to 'Editar', edit_product_path(product) %></td>
	  <td>&emsp;</td>
          <td><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Tem certeza que quer excluir?' } %></td>
<td>&emsp;</td>

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_product_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :product_nome %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :product_tipo %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :product_estado %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :product_descricao %>
  </div>

<br>
<br>

  <div class="field">
    <%= form.label :avatar %><br>
    <%= form.file_field :avatar %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/products/edit.html.erb
<br>
<br>
<h1>Editando Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Mostrar', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<h1>Produtos</h1>

<table>
  <thead>
    <tr>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Nome</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Tipo</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Estado</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Descrição</th>
	<td>&emsp;</td>
	<td>&emsp;</td>
      <th>Doador</th>
      <thcolspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.nome %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.tipo %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.estado %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.descricao %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= product.doador %></td>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
	<td>&emsp;</td>
        <td><%= link_to 'Mostrar', product %></td>
	<td>&emsp;</td>

	<% if user_signed_in? && product.doador != current_user.nome %>
	   <td><%= link_to 'EUQUERO', eu_quero_index_path %></td>
	<% end %>
	<% if user_signed_in? && product.doador == current_user.nome %>
          <td><%= link_to 'Editar', edit_product_path(product) %></td>
	  <td>&emsp;</td>
          <td><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Tem certeza que quer excluir?' } %></td>
<td>&emsp;</td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_product_path %>

app/views/products/new.html.erb
<br>
<br>
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<br>

<p>
  <%= image_tag @product.avatar.url(:medium) %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @product.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @product.tipo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @product.estado %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @product.descricao %>
</p>







<% if @product.doador == nil %>
  <% @product.doador = current_user.nome %>
  <% @product.save %>
<% end %>


<p>
  <strong>Doador:</strong>
  <%= @product.doador %>
</p>

<% if user_signed_in? && @product.doador == current_user.nome%>
   <%= link_to 'Editar', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Voltar', products_path %>
<br>
<br>